---
title: "&#32;"
output:
  html_document:
    css: ["communityreport.css"]
params:
  community_html: NA
  map: NULL
  plot: NA
  footer: NULL
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r report_html, results='asis'}
shiny::HTML(params$community_html)
```

```{r map_section, echo=FALSE}
if (!(is.null(params$map) || anyNA(params$map) || length(params$map) == 0)) {
  params$map
}
```

```{r plot, fig.align='center', out.width='100%'}
params$plot
```

```{r footer, fig.align='center', out.width='100%'}
if (is.null(params$footer)) {
  footer <- (
    shiny::div(
      style = "background-color: #edeff0; color: black; width: 100%; padding: 10px 20px; 
  text-align: right; margin: 10px 0;", 
  
  shiny::p(style = "margin-bottom: 0",
           paste("Version", EJAM:::global_or_param("app_version"),
                 "| Report created on",
                 ifelse(
                   isTRUE(getOption("shiny.testmode")),
                   "[SHINYTEST DATE]", # so the snapshot of the report is consistent, not diff date each time tested
                   format(Sys.Date(), "%B %d, %Y")
                 )
           )
  )
    ) 
  )
} else {
  footer <- params$footer
}

footer

```
