#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_regid.R or similar files

#' @name testinput_regid
#' @docType data
#' @title test data, EPA Facility Registry ID numbers to try using
#' @details Just for convenience, installed with the package
'testinput_regid'
