#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_fips_mix.R or similar files

#' @name testinput_fips_mix
#' @docType data
#' @title testinput_fips_mix dataset
#' @description Census FIPS codes vector as example, e.g., mapfast(shapes_from_fips(testinput_fips_mix))
'testinput_fips_mix'
