# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# lintr provides static code analysis for R.
# It checks for adherence to a given style,
# identifying syntax errors and possible semantic issues,
# then reports them to you so you can take action.

# More details at https://lintr.r-lib.org/

# ## to use just a subset of the most important checks:
## see  EJAM/R/utils_lint_trailing_spaces.R
#  mine = c(
#     linters_with_tags('common_mistakes'),
#     list( # correctness minus object usage
#       duplicate_argument_linter(),
#       equals_na_linter(),
#       missing_argument_linter(),
#       namespace_linter(),
#       package_hooks_linter(),
#       sprintf_linter()
#     )
#   )
#   # ### but not "object_usage_linter"

name: lintr

on:
  push:
    branches: [ "development" ]
#    branches: [ "lintr-workflow", "development" ]
#  pull_request:
#    # The branches below must be a subset of the branches above
#    branches: [ "development" ]
  schedule:
    - cron: '40 7 * * 2'
#     eg every 2 weeks

permissions:
  contents: read

jobs:
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:

      - name: Checkout EJAM code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup lintr
        uses: r-lib/actions/setup-r-dependencies@813ef1cb62cf0b4b51a044419024c37807fa8095
        with:
          cache: false
          extra-packages: lintr

      - name: Run lintr
        run: lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif")
        shell: Rscript {0}
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true
